In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv("qoute_dataset.csv")

In [5]:
df.head(

)

                                               quote           Author
0  “The world as we have created it is a process ...  Albert Einstein
1  “It is our choices, Harry, that show what we t...     J.K. Rowling
2  “There are only two ways to live your life. On...  Albert Einstein
3  “The person, be it gentleman or lady, who has ...      Jane Austen
4  “Imperfection is beauty, madness is genius and...   Marilyn Monroe

In [6]:
df.shape

(3038, 2)

In [7]:
df.isna().sum()

quote     0
Author    0
dtype: int64

In [8]:
quote= df['quote']
quote.head()

0    “The world as we have created it is a process ...
1    “It is our choices, Harry, that show what we t...
2    “There are only two ways to live your life. On...
3    “The person, be it gentleman or lady, who has ...
4    “Imperfection is beauty, madness is genius and...
Name: quote, dtype: object

In [9]:
df['quote'] = df['quote'].str.lower()

In [10]:
df['quote']

0       “the world as we have created it is a process ...
1       “it is our choices, harry, that show what we t...
2       “there are only two ways to live your life. on...
3       “the person, be it gentleman or lady, who has ...
4       “imperfection is beauty, madness is genius and...
                              ...
3033        the past beats inside me like a second heart.
3034    damn, claire. warn a guy before you do a face-...
3035    can you be a girl for a few seconds?""i'm alwa...
3036    that's what fiction is for. it's for getting a...
3037    if we have no peace, it is because we have for...
Name: quote, Length: 3038, dtype: object

In [11]:
import re

In [12]:
def remove_punctuation(text):
  return re.sub(r"[^a-zA-Z0-1\s]","",text)
df['quote'] = df['quote'].apply(remove_punctuation)

In [13]:
def remove_HTMLtag(text):
  return re.sub(r"<*?>","",text)
df['quote'] = df['quote'].apply(remove_HTMLtag)

In [14]:
def remove_url(text):
  return re.sub(r"https\S+","",text)
df['quote'] = df['quote'].apply(remove_url)

In [15]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [16]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(quote)
vocab_size = len(tokenizer.word_index) + 1

In [17]:
word_index = tokenizer.word_index
print(len(word_index))
list(word_index.items())[:10]

8213

[('the', 1),
 ('you', 2),
 ('to', 3),
 ('and', 4),
 ('a', 5),
 ('i', 6),
 ('is', 7),
 ('of', 8),
 ('that', 9),
 ('it', 10)]

In [18]:
Sequence = tokenizer.texts_to_sequences(quote)

In [19]:
for i in range(4):
  print(quote[i])

“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”
“It is our choices, Harry, that show what we truly are, far more than our abilities.”
“There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”
“The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”

In [20]:
for i in range(4):
  print(Sequence[i])

[732, 61, 30, 19, 17, 901, 10, 7, 5, 1188, 8, 71, 290, 10, 149, 12, 835, 103, 776, 71, 290, 136]
[977, 7, 71, 902, 388, 9, 431, 21, 19, 479, 14, 299, 51, 55, 71, 2545, 136]
[1384, 14, 53, 203, 700, 3, 80, 15, 37, 36, 7, 30, 300, 92, 7, 5, 1073, 1, 104, 7, 30, 300, 126, 7, 5, 1073, 136]
[732, 118, 12, 10, 2546, 33, 1074, 31, 82, 13, 619, 11, 5, 74, 1385, 119, 12, 2547, 334, 136]

In [21]:
X=[]
y=[]

for seq in Sequence:
  for i in range(1,len(seq)):
    input_seq = seq[:i]
    output_seq = seq[i]
    X.append(input_seq)
    y.append(output_seq)

In [22]:
X

[[732],
 [732, 61],
 [732, 61, 30],
 [732, 61, 30, 19],
 [732, 61, 30, 19, 17],
 [732, 61, 30, 19, 17, 901],
 [732, 61, 30, 19, 17, 901, 10],
 [732, 61, 30, 19, 17, 901, 10, 7],
 [732, 61, 30, 19, 17, 901, 10, 7, 5],
 [732, 61, 30, 19, 17, 901, 10, 7, 5, 1188],
 [732, 61, 30, 19, 17, 901, 10, 7, 5, 1188, 8],
 [732, 61, 30, 19, 17, 901, 10, 7, 5, 1188, 8, 71],
 [732, 61, 30, 19, 17, 901, 10, 7, 5, 1188, 8, 71, 290],
 [732, 61, 30, 19, 17, 901, 10, 7, 5, 1188, 8, 71, 290, 10],
 [732, 61, 30, 19, 17, 901, 10, 7, 5, 1188, 8, 71, 290, 10, 149],
 [732, 61, 30, 19, 17, 901, 10, 7, 5, 1188, 8, 71, 290, 10, 149, 12],
 [732, 61, 30, 19, 17, 901, 10, 7, 5, 1188, 8, 71, 290, 10, 149, 12, 835],
 [732, 61, 30, 19, 17, 901, 10, 7, 5, 1188, 8, 71, 290, 10, 149, 12, 835, 103],
 [732,
  61,
  30,
  19,
  17,
  901,
  10,
  7,
  5,
  1188,
  8,
  71,
  290,
  10,
  149,
  12,
  835,
  103,
  776],
 [732,
  61,
  30,
  19,
  17,
  901,
  10,
  7,
  5,
  1188,
  8,
  71,
  290,
  10,
  149,
  12,
  835,
  103,
  776,
  71],
 [732,
  61,
  30,
  19,
  17,
  901,
  10,
  7,
  5,
  1188,
  8,
  71,
  290,
  10,
  149,
  12,
  835,
  103,
  776,
  71,
  290],
 [977],
 [977, 7],
 [977, 7, 71],
 [977, 7, 71, 902],
 [977, 7, 71, 902, 388],
 [977, 7, 71, 902, 388, 9],
 [977, 7, 71, 902, 388, 9, 431],
 [977, 7, 71, 902, 388, 9, 431, 21],
 [977, 7, 71, 902, 388, 9, 431, 21, 19],
 [977, 7, 71, 902, 388, 9, 431, 21, 19, 479],
 [977, 7, 71, 902, 388, 9, 431, 21, 19, 479, 14],
 [977, 7, 71, 902, 388, 9, 431, 21, 19, 479, 14, 299],
 [977, 7, 71, 902, 388, 9, 431, 21, 19, 479, 14, 299, 51],
 [977, 7, 71, 902, 388, 9, 431, 21, 19, 479, 14, 299, 51, 55],
 [977, 7, 71, 902, 388, 9, 431, 21, 19, 479, 14, 299, 51, 55, 71],
 [977, 7, 71, 902, 388, 9, 431, 21, 19, 479, 14, 299, 51, 55, 71, 2545],
 [1384],
 [1384, 14],
 [1384, 14, 53],
 [1384, 14, 53, 203],
 [1384, 14, 53, 203, 700],
 [1384, 14, 53, 203, 700, 3],
 [1384, 14, 53, 203, 700, 3, 80],
 [1384, 14, 53, 203, 700, 3, 80, 15],
 [1384, 14, 53, 203, 700, 3, 80, 15, 37],
 [1384, 14, 53, 203, 700, 3, 80, 15, 37, 36],
 [1384, 14, 53, 203, 700, 3, 80, 15, 37, 36, 7],
 [1384, 14, 53, 203, 700, 3, 80, 15, 37, 36, 7, 30],
 [1384, 14, 53, 203, 700, 3, 80, 15, 37, 36, 7, 30, 300],
 [1384, 14, 53, 203, 700, 3, 80, 15, 37, 36, 7, 30, 300, 92],
 [1384, 14, 53, 203, 700, 3, 80, 15, 37, 36, 7, 30, 300, 92, 7],
 [1384, 14, 53, 203, 700, 3, 80, 15, 37, 36, 7, 30, 300, 92, 7, 5],
 [1384, 14, 53, 203, 700, 3, 80, 15, 37, 36, 7, 30, 300, 92, 7, 5, 1073],
 [1384, 14, 53, 203, 700, 3, 80, 15, 37, 36, 7, 30, 300, 92, 7, 5, 1073, 1],
 [1384,
  14,
  53,
  203,
  700,
  3,
  80,
  15,
  37,
  36,
  7,
  30,
  300,
  92,
  7,
  5,
  1073,
  1,
  104],
 [1384,
  14,
  53,
  203,
  700,
  3,
  80,
  15,
  37,
  36,
  7,
  30,
  300,
  92,
  7,
  5,
  1073,
  1,
  104,
  7],
 [1384,
  14,
  53,
  203,
  700,
  3,
  80,
  15,
  37,
  36,
  7,
  30,
  300,
  92,
  7,
  5,
  1073,
  1,
  104,
  7,
  30],
 [1384,
  14,
  53,
  203,
  700,
  3,
  80,
  15,
  37,
  36,
  7,
  30,
  300,
  92,
  7,
  5,
  1073,
  1,
  104,
  7,
  30,
  300],
 [1384,
  14,
  53,
  203,
  700,
  3,
  80,
  15,
  37,
  36,
  7,
  30,
  300,
  92,
  7,
  5,
  1073,
  1,
  104,
  7,
  30,
  300,
  126],
 [1384,
  14,
  53,
  203,
  700,
  3,
  80,
  15,
  37,
  36,
  7,
  30,
  300,
  92,
  7,
  5,
  1073,
  1,
  104,
  7,
  30,
  300,
  126,
  7],
 [1384,
  14,
  53,
  203,
  700,
  3,
  80,
  15,
  37,
  36,
  7,
  30,
  300,
  92,
  7,
  5,
  1073,
  1,
  104,
  7,
  30,
  300,
  126,
  7,
  5],
 [1384,
  14,
  53,
  203,
  700,
  3,
  80,
  15,
  37,
  36,
  7,
  30,
  300,
  92,
  7,
  5,
  1073,
  1,
  104,
  7,
  30,
  300,
  126,
  7,
  5,
  1073],
 [732],
 [732, 118],
 [732, 118, 12],
 [732, 118, 12, 10],
 [732, 118, 12, 10, 2546],
 [732, 118, 12, 10, 2546, 33],
 [732, 118, 12, 10, 2546, 33, 1074],
 [732, 118, 12, 10, 2546, 33, 1074, 31],
 [732, 118, 12, 10, 2546, 33, 1074, 31, 82],
 [732, 118, 12, 10, 2546, 33, 1074, 31, 82, 13],
 [732, 118, 12, 10, 2546, 33, 1074, 31, 82, 13, 619],
 [732, 118, 12, 10, 2546, 33, 1074, 31, 82, 13, 619, 11],
 [732, 118, 12, 10, 2546, 33, 1074, 31, 82, 13, 619, 11, 5],
 [732, 118, 12, 10, 2546, 33, 1074, 31, 82, 13, 619, 11, 5, 74],
 [732, 118, 12, 10, 2546, 33, 1074, 31, 82, 13, 619, 11, 5, 74, 1385],
 [732, 118, 12, 10, 2546, 33, 1074, 31, 82, 13, 619, 11, 5, 74, 1385, 119],
 [732, 118, 12, 10, 2546, 33, 1074, 31, 82, 13, 619, 11, 5, 74, 1385, 119, 12],
 [732,
  118,
  12,
  10,
  2546,
  33,
  1074,
  31,
  82,
  13,
  619,
  11,
  5,
  74,
  1385,
  119,
  12,
  2547],
 [732,
  118,
  12,
  10,
  2546,
  33,
  1074,
  31,
  82,
  13,
  619,
  11,
  5,
  74,
  1385,
  119,
  12,
  2547,
  334],
 [3778],
 [3778, 7],
 [3778, 7, 318],
 [3778, 7, 318, 777],
 [3778, 7, 318, 777, 7],
 [3778, 7, 318, 777, 7, 654],
 [3778, 7, 318, 777, 7, 654, 4],
 [3778, 7, 318, 777, 7, 654, 4, 56],
 [3778, 7, 318, 777, 7, 654, 4, 56, 147],
 [3778, 7, 318, 777, 7, 654, 4, 56, 147, 3],
 [3778, 7, 318, 777, 7, 654, 4, 56, 147, 3, 12],
 [3778, 7, 318, 777, 7, 654, 4, 56, 147, 3, 12, 701],
 [3778, 7, 318, 777, 7, 654, 4, 56, 147, 3, 12, 701, 1189],
 [3778, 7, 318, 777, 7, 654, 4, 56, 147, 3, 12, 701, 1189, 55],
 [3778, 7, 318, 777, 7, 654, 4, 56, 147, 3, 12, 701, 1189, 55, 701],
 [3778, 7, 318, 777, 7, 654, 4, 56, 147, 3, 12, 701, 1189, 55, 701, 778],
 [3779],
 [3779, 13],
 [3779, 13, 3],
 [3779, 13, 3, 205],
 [3779, 13, 3, 205, 5],
 [3779, 13, 3, 205, 5, 89],
 [3779, 13, 3, 205, 5, 89, 8],
 [3779, 13, 3, 205, 5, 89, 8, 448],
 [3779, 13, 3, 205, 5, 89, 8, 448, 283],
 [3779, 13, 3, 205, 5, 89, 8, 448, 283, 205],
 [3779, 13, 3, 205, 5, 89, 8, 448, 283, 205, 5],
 [3779, 13, 3, 205, 5, 89, 8, 448, 283, 205, 5, 89],
 [3779, 13, 3, 205, 5, 89, 8, 448, 283, 205, 5, 89, 8],
 [3779, 13, 3, 205, 5, 89, 8, 448, 283, 205, 5, 89, 8, 536],
 [977],
 [977, 7],
 [977, 7, 147],
 [977, 7, 147, 3],
 [977, 7, 147, 3, 12],
 [977, 7, 147, 3, 12, 1386],
 [977, 7, 147, 3, 12, 1386, 18],
 [977, 7, 147, 3, 12, 1386, 18, 21],
 [977, 7, 147, 3, 12, 1386, 18, 21, 2],
 [977, 7, 147, 3, 12, 1386, 18, 21, 2, 14],
 [977, 7, 147, 3, 12, 1386, 18, 21, 2, 14, 55],
 [977, 7, 147, 3, 12, 1386, 18, 21, 2, 14, 55, 3],
 [977, 7, 147, 3, 12, 1386, 18, 21, 2, 14, 55, 3, 12],
 [977, 7, 147, 3, 12, 1386, 18, 21, 2, 14, 55, 3, 12, 179],
 [977, 7, 147, 3, 12, 1386, 18, 21, 2, 14, 55, 3, 12, 179, 18],
 [977, 7, 147, 3, 12, 1386, 18, 21, 2, 14, 55, 3, 12, 179, 18, 21],
 [977, 7, 147, 3, 12, 1386, 18, 21, 2, 14, 55, 3, 12, 179, 18, 21, 2],
 [977, 7, 147, 3, 12, 1386, 18, 21, 2, 14, 55, 3, 12, 179, 18, 21, 2, 14],
 [977, 7, 147, 3, 12, 1386, 18, 21, 2, 14, 55, 3, 12, 179, 18, 21, 2, 14, 13],
 [733],
 [733, 17],
 [733, 17, 13],
 [733, 17, 13, 1387],
 [733, 17, 13, 1387, 188],
 [733, 17, 13, 1387, 188, 50],
 [733, 17, 13, 1387, 188, 50, 432],
 [733, 17, 13, 1387, 188, 50, 432, 1190],
 [733, 17, 13, 1387, 188, 50, 432, 1190, 2011],
 [733, 17, 13, 1387, 188, 50, 432, 1190, 2011, 700],
 [733, 17, 13, 1387, 188, 50, 432, 1190, 2011, 700, 9],
 [733, 17, 13, 1387, 188, 50, 432, 1190, 2011, 700, 9, 403],
 [733, 17, 13, 1387, 188, 50, 432, 1190, 2011, 700, 9, 403, 279],
 [1075],
 [1075, 185],
 [1075, 185, 7],
 [1075, 185, 7, 39],
 [1075, 185, 7, 39, 5],
 [1075, 185, 7, 39, 5, 836],
 [1075, 185, 7, 39, 5, 836, 1388],
 [1075, 185, 7, 39, 5, 836, 1388, 2],
 [1075, 185, 7, 39, 5, 836, 1388, 2, 46],
 [1075, 185, 7, 39, 5, 836, 1388, 2, 46, 49],
 [1075, 185, 7, 39, 5, 836, 1388, 2, 46, 49, 60],
 [1075, 185, 7, 39, 5, 836, 1388, 2, 46, 49, 60, 326],
 [1075, 185, 7, 39, 5, 836, 1388, 2, 46, 49, 60, 326, 10],
 [1075, 185, 7, 39, 5, 836, 1388, 2, 46, 49, 60, 326, 10, 7],
 [1075, 185, 7, 39, 5, 836, 1388, 2, 46, 49, 60, 326, 10, 7, 172],
 [1075, 185, 7, 39, 5, 836, 1388, 2, 46, 49, 60, 326, 10, 7, 172, 56],
 [1075, 185, 7, 39, 5, 836, 1388, 2, 46, 49, 60, 326, 10, 7, 172, 56, 11],
 [1075, 185, 7, 39, 5, 836, 1388, 2, 46, 49, 60, 326, 10, 7, 172, 56, 11, 620],
 [1075,
  185,
  7,
  39,
  5,
  836,
  1388,
  2,
  46,
  49,
  60,
  326,
  10,
  7,
  172,
  56,
  11,
  620,
  480],
 [1075],
 [1075, 105],
 [1075, 105, 103],
 [1075, 105, 103, 1076],
 [1075, 105, 103, 1076, 7],
 [1075, 105, 103, 1076, 7, 39],
 [1075, 105, 103, 1076, 7, 39, 2],
 [1075, 105, 103, 1076, 7, 39, 2, 49],
 [1075, 105, 103, 1076, 7, 39, 2, 49, 261],
 [2548],
 [2548, 37],
 [2548, 37, 7],
 [2548, 37, 7, 21],
 [2548, 37, 7, 21, 2],
 [2548, 37, 7, 21, 2, 65],
 [2548, 37, 7, 21, 2, 65, 10],
 [2548, 37, 7, 21, 2, 65, 10, 45],
 [2548, 37, 7, 21, 2, 65, 10, 45, 189],
 [2548, 37, 7, 21, 2, 65, 10, 45, 189, 21],
 [2548, 37, 7, 21, 2, 65, 10, 45, 189, 21, 96],
 [2548, 37, 7, 21, 2, 65, 10, 45, 189, 21, 96, 131],
 [2548, 37, 7, 21, 2, 65, 10, 45, 189, 21, 96, 131, 3],
 [2548, 37, 7, 21, 2, 65, 10, 45, 189, 21, 96, 131, 3, 779],
 [2548, 37, 7, 21, 2, 65, 10, 45, 189, 21, 96, 131, 3, 779, 57],
 [2548, 37, 7, 21, 2, 65, 10, 45, 189, 21, 96, 131, 3, 779, 57, 124],
 [2548, 37, 7, 21, 2, 65, 10, 45, 189, 21, 96, 131, 3, 779, 57, 124, 56],
 [2548, 37, 7, 21, 2, 65, 10, 45, 189, 21, 96, 131, 3, 779, 57, 124, 56, 5],
 [2548,
  37,
  7,
  21,
  2,
  65,
  10,
  45,
  189,
  21,
  96,
  131,
  3,
  779,
  57,
  124,
  56,
  5,
  2012],
 [2548,
  37,
  7,
  21,
  2,
  65,
  10,
  45,
  189,
  21,
  96,
  131,
  3,
  779,
  57,
  124,
  56,
  5,
  2012,
  177],
 [2548,
  37,
  7,
  21,
  2,
  65,
  10,
  45,
  189,
  21,
  96,
  131,
  3,
  779,
  57,
  124,
  56,
  5,
  2012,
  177,
  16],
 [2548,
  37,
  7,
  21,
  2,
  65,
  10,
  45,
  189,
  21,
  96,
  131,
  3,
  779,
  57,
  124,
  56,
  5,
  2012,
  177,
  16,
  1],
 [2548,
  37,
  7,
  21,
  2,
  65,
  10,
  45,
  189,
  21,
  96,
  131,
  3,
  779,
  57,
  124,
  56,
  5,
  2012,
  177,
  16,
  1,
  74],
 [2548,
  37,
  7,
  21,
  2,
  65,
  10,
  45,
  189,
  21,
  96,
  131,
  3,
  779,
  57,
  124,
  56,
  5,
  2012,
  177,
  16,
  1,
  74,
  214],
 [2548,
  37,
  7,
  21,
  2,
  65,
  10,
  45,
  189,
  21,
  96,
  131,
  3,
  779,
  57,
  124,
  56,
  5,
  2012,
  177,
  16,
  1,
  74,
  214,
  7],
 [2548,
  37,
  7,
  21,
  2,
  65,
  10,
  45,
  189,
  21,
  96,
  131,
  3,
  779,
  57,
  124,
  56,
  5,
  2012,
  177,
  16,
  1,
  74,
  214,
  7,
  2],
 [2548,
  37,
  7,
  21,
  2,
  65,
  10,
  45,
  189,
  21,
  96,
  131,
  3,
  779,
  57,
  124,
  56,
  5,
  2012,
  177,
  16,
  1,
  74,
  214,
  7,
  2,
  93],
 [2548,
  37,
  7,
  21,
  2,
  65,
  10,
  45,
  189,
  21,
  96,
  131,
  3,
  779,
  57,
  124,
  56,
  5,
  2012,
  177,
  16,
  1,
  74,
  214,
  7,
  2,
  93,
  3],
 [2548,
  37,
  7,
  21,
  2,
  65,
  10,
  45,
  189,
  21,
  96,
  131,
  3,
  779,
  57,
  124,
  56,
  5,
  2012,
  177,
  16,
  1,
  74,
  214,
  7,
  2,
  93,
  3,
  481],
 [2548,
  37,
  7,
  21,
  2,
  65,
  10,
  45,
  189,
  21,
  96,
  131,
  3,
  779,
  57,
  124,
  56,
  5,
  2012,
  177,
  16,
  1,
  74,
  214,
  7,
  2,
  93,
  3,
  481,
  60],
 [2548,
  37,
  7,
  21,
  2,
  65,
  10,
  45,
  189,
  21,
  96,
  131,
  3,
  779,
  57,
  124,
  56,
  5,
  2012,
  177,
  16,
  1,
  74,
  214,
  7,
  2,
  93,
  3,
  481,
  60,
  96],
 [2548,
  37,
  7,
  21,
  2,
  65,
  10,
  45,
  189,
  21,
  96,
  131,
  3,
  779,
  57,
  124,
  56,
  5,
  2012,
  177,
  16,
  1,
  74,
  214,
  7,
  2,
  93,
  3,
  481,
  60,
  96,
  131],
 [2548,
  37,
  7,
  21,
  2,
  65,
  10,
  45,
  189,
  21,
  96,
  131,
  3,
  779,
  57,
  124,
  56,
  5,
  2012,
  177,
  16,
  1,
  74,
  214,
  7,
  2,
  93,
  3,
  481,
  60,
  96,
  131,
  3],
 [2548,
  37,
  7,
  21,
  2,
  65,
  10,
  45,
  189,
  21,
  96,
  131,
  3,
  779,
  57,
  124,
  56,
  5,
  2012,
  177,
  16,
  1,
  74,
  214,
  7,
  2,
  93,
  3,
  481,
  60,
  96,
  131,
  3,
  779],
 [2548,
  37,
  7,
  21,
  2,
  65,
  10,
  45,
  189,
  21,
  96,
  131,
  3,
  779,
  57,
  124,
  56,
  5,
  2012,
  177,
  16,
  1,
  74,
  214,
  7,
  2,
  93,
  3,
  481,
  60,
  96,
  131,
  3,
  779,
  10],
 [2548,
  37,
  7,
  21,
  2,
  65,
  10,
  45,
  189,
  21,
  96,
  131,
  3,
  779,
  57,
  124,
  56,
  5,
  2012,
  177,
  16,
  1,
  74,
  214,
  7,
  2,
  93,
  3,
  481,
  60,
  96,
  131,
  3,
  779,
  10,
  57],
 [2548,
  37,
  7,
  21,
  2,
  65,
  10,
  45,
  189,
  21,
  96,
  131,
  3,
  779,
  57,
  124,
  56,
  5,
  2012,
  177,
  16,
  1,
  74,
  214,
  7,
  2,
  93,
  3,
  481,
  60,
  96,
  131,
  3,
  779,
  10,
  57,
  557],
 [2548,
  37,
  7,
  21,
  2,
  65,
  10,
  45,
  189,
  21,
  96,
  131,
  3,
  779,
  57,
  124,
  56,
  5,
  2012,
  177,
  16,
  1,
  74,
  214,
  7,
  2,
  93,
  3,
  481,
  60,
  96,
  131,
  3,
  779,
  10,
  57,
  557,
  28],
 [2548,
  37,
  7,
  21,
  2,
  65,
  10,
  45,
  189,
  21,
  96,
  131,
  3,
  779,
  57,
  124,
  56,
  5,
  2012,
  177,
  16,
  1,
  74,
  214,
  7,
  2,
  93,
  3,
  481,
  60,
  96,
  131,
  3,
  779,
  10,
  57,
  557,
  28,
  12],
 [2548,
  37,
  7,
  21,
  2,
  65,
  10,
  45,
  189,
  21,
  96,
  131,
  3,
  779,
  57,
  124,
  56,
  5,
  2012,
  177,
  16,
  1,
  74,
  214,
  7,
  2,
  93,
  3,
  481,
  60,
  96,
  131,
  3,
  779,
  10,
  57,
  557,
  28,
  12,
  15],
 [2548,
  37,
  7,
  21,
  2,
  65,
  10,
  45,
  189,
  21,
  96,
  131,
  3,
  779,
  57,
  124,
  56,
  5,
  2012,
  177,
  16,
  1,
  74,
  214,
  7,
  2,
  93,
  3,
  481,
  60,
  96,
  131,
  3,
  779,
  10,
  57,
  557,
  28,
  12,
  15,
  227],
 [2548,
  37,
  7,
  21,
  2,
  65,
  10,
  45,
  189,
  21,
  96,
  131,
  3,
  779,
  57,
  124,
  56,
  5,
  2012,
  177,
  16,
  1,
  74,
  214,
  7,
  2,
  93,
  3,
  481,
  60,
  96,
  131,
  3,
  779,
  10,
  57,
  557,
  28,
  12,
  15,
  227,
  978],
 [2548,
  37,
  7,
  21,
  2,
  65,
  10,
  45,
  189,
  21,
  96,
  131,
  3,
  779,
  57,
  124,
  56,
  5,
  2012,
  177,
  16,
  1,
  74,
  214,
  7,
  2,
  93,
  3,
  481,
  60,
  96,
  131,
  3,
  779,
  10,
  57,
  557,
  28,
  12,
  15,
  227,
  978,
  517],
 [2548,
  37,
  7,
  21,
  2,
  65,
  10,
  45,
  189,
  21,
  96,
  131,
  3,
  779,
  57,
  124,
  56,
  5,
  2012,
  177,
  16,
  1,
  74,
  214,
  7,
  2,
  93,
  3,
  481,
  60,
  96,
  131,
  3,
  779,
  10,
  57,
  557,
  28,
  12,
  15,
  227,
  978,
  517,
  39],
 [2548,
  37,
  7,
  21,
  2,
  65,
  10,
  45,
  189,
  21,
  96,
  131,
  3,
  779,
  57,
  124,
  56,
  5,
  2012,
  177,
  16,
  1,
  74,
  214,
  7,
  2,
  93,
  3,
  481,
  60,
  96,
  131,
  3,
  779,
  10,
  57,
  557,
  28,
  12,
  15,
  227,
  978,
  517,
  39,
  10],
 [2548,
  37,
  7,
  21,
  2,
  65,
  10,
  45,
  189,
  21,
  96,
  131,
  3,
  779,
  57,
  124,
  56,
  5,
  2012,
  177,
  16,
  1,
  74,
  214,
  7,
  2,
  93,
  3,
  481,
  60,
  96,
  131,
  3,
  779,
  10,
  57,
  557,
  28,
  12,
  15,
  227,
  978,
  517,
  39,
  10,
  780],
 [2548,
  37,
  7,
  21,
  2,
  65,
  10,
  45,
  189,
  21,
  96,
  131,
  3,
  779,
  57,
  124,
  56,
  5,
  2012,
  177,
  16,
  1,
  74,
  214,
  7,
  2,
  93,
  3,
  481,
  60,
  96,
  131,
  3,
  779,
  10,
  57,
  557,
  28,
  12,
  15,
  227,
  978,
  517,
  39,
  10,
  780,
  16],
 [2548,
  37,
  7,
  21,
  2,
  65,
  10,
  45,
  189,
  21,
  96,
  131,
  3,
  779,
  57,
  124,
  56,
  5,
  2012,
  177,
  16,
  1,
  74,
  214,
  7,
  2,
  93,
  3,
  481,
  60,
  96,
  131,
  3,
  779,
  10,
  57,
  557,
  28,
  12,
  15,
  227,
  978,
  517,
  39,
  10,
  780,
  16,
  50],
 [2548,
  37,
  7,
  21,
  2,
  65,
  10,
  45,
  189,
  21,
  96,
  131,
  3,
  779,
  57,
  124,
  56,
  5,
  2012,
  177,
  16,
  1,
  74,
  214,
  7,
  2,
  93,
  3,
  481,
  60,
  96,
  131,
  3,
  779,
  10,
  57,
  557,
  28,
  12,
  15,
  227,
  978,
  517,
  39,
  10,
  780,
  16,
  50,
  156],
 [2548,
  37,
  7,
  21,
  2,
  65,
  10,
  45,
  189,
  21,
  96,
  131,
  3,
  779,
  57,
  124,
  56,
  5,
  2012,
  177,
  16,
  1,
  74,
  214,
  7,
  2,
  93,
  3,
  481,
  60,
  96,
  131,
  3,
  779,
  10,
  57,
  557,
  28,
  12,
  15,
  227,
  978,
  517,
  39,
  10,
  780,
  16,
  50,
  156,
  87],
 [2548,
  37,
  7,
  21,
  2,
  65,
  10,
  45,
  189,
  21,
  96,
  131,
  3,
  779,
  57,
  124,
  56,
  5,
  2012,
  177,
  16,
  1,
  74,
  214,
  7,
  2,
  93,
  3,
  481,
  60,
  96,
  131,
  3,
  779,
  10,
  57,
  557,
  28,
  12,
  15,
  227,
  978,
  517,
  39,
  10,
  780,
  16,
  50,
  156,
  87,
  134],
 [2548,
  37,
  7,
  21,
  2,
  65,
  10,
  45,
  189,
  21,
  96,
  131,
  3,
  779,
  57,
  124,
  56,
  5,
  2012,
  177,
  16,
  1,
  74,
  214,
  7,
  2,
  93,
  3,
  481,
  60,
  96,
  131,
  3,
  779,
  10,
  57,
  557,
  28,
  12,
  15,
  227,
  978,
  517,
  39,
  10,
  780,
  16,
  50,
  156,
  87,
  134,
  87],
 [2548,
  37,
  7,
  21,
  2,
  65,
  10,
  45,
  189,
  21,
  96,
  131,
  3,
  779,
  57,
  124,
  56,
  5,
  2012,
  177,
  16,
  1,
  74,
  214,
  7,
  2,
  93,
  3,
  481,
  60,
  96,
  131,
  3,
  779,
  10,
  57,
  557,
  28,
  12,
  15,
  227,
  978,
  517,
  39,
  10,
  780,
  16,
  50,
  156,
  87,
  134,
  87,
  79],
 [2548,
  37,
  7,
  21,
  2,
  65,
  10,
  45,
  189,
  21,
  96,
  131,
  3,
  779,
  57,
  124,
  56,
  5,
  2012,
  177,
  16,
  1,
  74,
  214,
  7,
  2,
  93,
  3,
  481,
  60,
  96,
  131,
  3,
  779,
  10,
  57,
  557,
  28,
  12,
  15,
  227,
  978,
  517,
  39,
  10,
  780,
  16,
  50,
  156,
  87,
  134,
  87,
  79,
  1],
 [2548,
  37,
  7,
  21,
  2,
  65,
  10,
  45,
  189,
  21,
  96,
  131,
  3,
  779,
  57,
  124,
  56,
  5,
  2012,
  177,
  16,
  1,
  74,
  214,
  7,
  2,
  93,
  3,
  481,
  60,
  96,
  131,
  3,
  779,
  10,
  57,
  557,
  28,
  12,
  15,
  227,
  978,
  517,
  39,
  10,
  780,
  16,
  50,
  156,
  87,
  134,
  87,
  79,
  1,
  284],
 [2548,
  37,
  7,
  21,
  2,
  65,
  10,
  45,
  189,
  21,
  96,
  131,
  3,
  779,
  57,
  124,
  56,
  5,
  2012,
  177,
  16,
  1,
  74,
  214,
  7,
  2,
  93,
  3,
  481,
  60,
  96,
  131,
  3,
  779,
  10,
  57,
  557,
  28,
  12,
  15,
  227,
  978,
  517,
  39,
  10,
  780,
  16,
  50,
  156,
  87,
  134,
  87,
  79,
  1,
  284,
  9],
 [2548,
  37,
  7,
  21,
  2,
  65,
  10,
  45,
  189,
  21,
  96,
  131,
  3,
  779,
  57,
  124,
  56,
  5,
  2012,
  177,
  16,
  1,
  74,
  214,
  7,
  2,
  93,
  3,
  481,
  60,
  96,
  131,
  3,
  779,
  10,
  57,
  557,
  28,
  12,
  15,
  227,
  978,
  517,
  39,
  10,
  780,
  16,
  50,
  156,
  87,
  134,
  87,
  79,
  1,
  284,
  9,
  280],
 [2548,
  37,
  7,
  21,
  2,
  65,
  10,
  45,
  189,
  21,
  96,
  131,
  3,
  779,
  57,
  124,
  56,
  5,
  2012,
  177,
  16,
  1,
  74,
  214,
  7,
  2,
  93,
  3,
  481,
  60,
  96,
  131,
  3,
  779,
  10,
  57,
  557,
  28,
  12,
  15,
  227,
  978,
  517,
  39,
  10,
  780,
  16,
  50,
  156,
  87,
  134,
  87,
  79,
  1,
  284,
  9,
  280,
  23],
 [2548,
  37,
  7,
  21,
  2,
  65,
  10,
  45,
  189,
  21,
  96,
  131,
  3,
  779,
  57,
  124,
  56,
  5,
  2012,
  177,
  16,
  1,
  74,
  214,
  7,
  2,
  93,
  3,
  481,
  60,
  96,
  131,
  3,
  779,
  10,
  57,
  557,
  28,
  12,
  15,
  227,
  978,
  517,
  39,
  10,
  780,
  16,
  50,
  156,
  87,
  134,
  87,
  79,
  1,
  284,
  9,
  280,
  23,
  2],
 [2548,
  37,
  7,
  21,
  2,
  65,
  10,
  45,
  189,
  21,
  96,
  131,
  3,
  779,
  57,
  124,
  56,
  5,
  2012,
  177,
  16,
  1,
  74,
  214,
  7,
  2,
  93,
  3,
  481,
  60,
  96,
  131,
  3,
  779,
  10,
  57,
  557,
  28,
  12,
  15,
  227,
  978,
  517,
  39,
  10,
  780,
  16,
  50,
  156,
  87,
  134,
  87,
  79,
  1,
  284,
  9,
  280,
  23,
  2,
  150],
 [2548,
  37,
  7,
  21,
  2,
  65,
  10,
  45,
  189,
  21,
  96,
  131,
  3,
  779,
  57,
  124,
  56,
  5,
  2012,
  177,
  16,
  1,
  74,
  214,
  7,
  2,
  93,
  3,
  481,
  60,
  96,
  131,
  3,
  779,
  10,
  57,
  557,
  28,
  12,
  15,
  227,
  978,
  517,
  39,
  10,
  780,
  16,
  50,
  156,
  87,
  134,
  87,
  79,
  1,
  284,
  9,
  280,
  23,
  2,
  150,
  126],
 [2548,
  37,
  7,
  21,
  2,
  65,
  10,
  45,
  189,
  21,
  96,
  131,
  3,
  779,
  57,
  124,
  56,
  5,
  2012,
  177,
  16,
  1,
  74,
  214,
  7,
  2,
  93,
  3,
  481,
  60,
  96,
  131,
  3,
  779,
  10,
  57,
  557,
  28,
  12,
  15,
  227,
  978,
  517,
  39,
  10,
  780,
  16,
  50,
  156,
  87,

In [23]:
y

[61,
 30,
 19,
 17,
 901,
 10,
 7,
 5,
 1188,
 8,
 71,
 290,
 10,
 149,
 12,
 835,
 103,
 776,
 71,
 290,
 136,
 7,
 71,
 902,
 388,
 9,
 431,
 21,
 19,
 479,
 14,
 299,
 51,
 55,
 71,
 2545,
 136,
 14,
 53,
 203,
 700,
 3,
 80,
 15,
 37,
 36,
 7,
 30,
 300,
 92,
 7,
 5,
 1073,
 1,
 104,
 7,
 30,
 300,
 126,
 7,
 5,
 1073,
 136,
 118,
 12,
 10,
 2546,
 33,
 1074,
 31,
 82,
 13,
 619,
 11,
 5,
 74,
 1385,
 119,
 12,
 2547,
 334,
 136,
 7,
 318,
 777,
 7,
 654,
 4,
 56,
 147,
 3,
 12,
 701,
 1189,
 55,
 701,
 778,
 136,
 13,
 3,
 205,
 5,
 89,
 8,
 448,
 283,
 205,
 5,
 89,
 8,
 536,
 136,
 7,
 147,
 3,
 12,
 1386,
 18,
 21,
 2,
 14,
 55,
 3,
 12,
 179,
 18,
 21,
 2,
 14,
 13,
 136,
 17,
 13,
 1387,
 188,
 50,
 432,
 1190,
 2011,
 700,
 9,
 403,
 279,
 136,
 185,
 7,
 39,
 5,
 836,
 1388,
 2,
 46,
 49,
 60,
 326,
 10,
 7,
 172,
 56,
 11,
 620,
 480,
 136,
 105,
 103,
 1076,
 7,
 39,
 2,
 49,
 261,
 136,
 37,
 7,
 21,
 2,
 65,
 10,
 45,
 189,
 21,
 96,
 131,
 3,
 779,
 57,
 124,
 56,
 5,
 2012,
 177,
 16,
 1,
 74,
 214,
 7,
 2,
 93,
 3,
 481,
 60,
 96,
 131,
 3,
 779,
 10,
 57,
 557,
 28,
 12,
 15,
 227,
 978,
 517,
 39,
 10,
 780,
 16,
 50,
 156,
 87,
 134,
 87,
 79,
 1,
 284,
 9,
 280,
 23,
 2,
 150,
 126,
 268,
 15,
 164,
 159,
 227,
 47,
 100,
 79,
 8,
 48,
 404,
 156,
 2549,
 65,
 1,
 159,
 227,
 11,
 1,
 61,
 30,
 18,
 1191,
 153,
 978,
 134,
 4,
 79,
 86,
 4,
 837,
 6,
 269,
 3,
 109,
 10,
 116,
 8,
 48,
 482,
 415,
 102,
 22,
 8,
 48,
 14,
 131,
 3,
 405,
 15,
 91,
 16,
 2,
 142,
 133,
 57,
 52,
 20,
 2,
 133,
 57,
 238,
 46,
 114,
 15,
 2550,
 238,
 46,
 114,
 9,
 335,
 31,
 218,
 2,
 251,
 4,
 9,
 433,
 18,
 126,
 50,
 52,
 2,
 655,
 182,
 186,
 270,
 96,
 1077,
 655,
 44,
 126,
 178,
 271,
 350,
 43,
 4,
 70,
 70,
 70,
 128,
 11,
 98,
 52,
 20,
 2,
 47,
 84,
 31,
 28,
 2551,
 41,
 178,
 15,
 301,
 416,
 178,
 15,
 1389,
 57,
 4,
 116,
 1612,
 178,
 781,
 52,
 838,
 5,
 195,
 90,
 4,
 206,
 41,
 102,
 3,
 285,
 66,
 136,
 351,
 5,
 154,
 656,
 8,
 903,
 3,
 319,
 57,
 3,
 71,
 734,
 16,
 50,
 30,
 102,
 3,
 319,
 57,
 3,
 71,
 227,
 136,
 2,
 142,
 904,
 10,
 3,
 5,
 905,
 449,
 257,
 2,
 47,
 224,
 10,
 98,
 136,
 139,
 13,
 12,
 77,
 180,
 77,
 265,
 33,
 77,
 53,
 76,
 179,
 175,
 76,
 139,
 24,
 161,
 16,
 20,
 76,
 228,
 2,
 146,
 21,
 176,
 589,
 590,
 13,
 2552,
 434,
 417,
 4,
 1,
 203,
 8,
 2,
 139,
 46,
 12,
 327,
 262,
 16,
 20,
 76,
 25,
 65,
 2,
 302,
 1080,
 2,
 3,
 64,
 979,
 4,
 980,
 3,
 129,
 192,
 4,
 371,
 381,
 350,
 981,
 77,
 4,
 133,
 77,
 1,
 116,
 2,
 25,
 76,
 139,
 13,
 12,
 290,
 66,
 2,
 88,
 435,
 8,
 1,
 105,
 16,
 76,
 28,
 133,
 2,
 5,
 214,
 8,
 77,
 9,
 76,
 274,
 2,
 25,
 2553,
 91,
 41,
 47,
 281,
 77,
 47,
 162,
 77,
 47,
 2013,
 4,
 47,
 466,
 51,
 55,
 76,
 25,
 133,
 285,
 27,
 76,
 218,
 2,
 196,
 100,
 77,
 49,
 27,
 76,
 218,
 2,
 436,
 4,
 591,
 77,
 27,
 590,
 13,
 40,
 136,
 39,
 839,
 10,
 1613,
 57,
 1,
 782,
 2014,
 621,
 7,
 5,
 622,
 2015,
 11,
 235,
 136,
 139,
 13,
 17,
 336,
 137,
 6,
 2554,
 3,
 79,
 16,
 6,
 64,
 6,
 17,
 2016,
 57,
 137,
 6,
 783,
 3,
 12,
 136,
 840,
 8,
 24,
 7,
 13,
 269,
 56,
 784,
 1,
 840,
 8,
 495,
 7,
 13,
 2017,
 56,
 784,
 1,
 840,
 8,
 592,
 7,
 13,
 2555,
 56,
 784,
 4,
 1,
 840,
 8,
 37,
 7,
 13,
 199,
 56,
 784,
 136,
 7,
 13,
 5,
 906,
 8,
 24,
 16,
 5,
 906,
 8,
 450,
 9,
 218,
 785,
 2556,
 136,
 227,
 74,
 115,
 4,
 5,
 2558,
 907,
 54,
 7,
 1,
 1614,
 37,
 136,
 7,
 21,
 337,
 3,
 75,
 236,
 19,
 14,
 371,
 104,
 1081,
 136,
 24,
 2,
 103,
 352,
 60,
 33,
 27,
 33,
 69,
 137,
 6,
 24,
 2,
 558,
 103,
 841,
 33,
 842,
 6,
 24,
 2,
 11,
 54,
 78,
 52,
 6,
 32,
 13,
 49,
 151,
 104,
 78,
 8,
 406,
 16,
 54,
 11,
 120,
 40,
 7,
 45,
 6,
 33,
 2,
 41,
 1390,
 9,
 15,
 308,
 252,
 26,
 735,
 7,
 26,
 308,
 41,
 1390,
 9,
 27,
 6,
 229,
 657,
 15,
 219,
 407,
 136,
 88,
 658,
 2,
 14,
 786,
 2,
 244,
 2019,
 1391,
 8,
 204,
 136,
 2,
 736,
 42,
 2,
 17,
 45,
 67,
 3,
 24,
 48,
 136,
 31,
 593,
 982,
 11,
 1615,
 25,
 65,
 2,
 5,
 1616,
 119,
 404,
 64,
 9,
 982,
 11,
 5,
 2020,
 25,
 65,
 2,
 5,
 843,
 136,
 7,
 11,
 1,
 659,
 8,
 1,
 1617,
 4,
 10,
 139,
 12,
 622,
 69,
 67,
 3,
 67,
 3,
 133,
 5,
 334,
 33,
 2021,
 1617,
 5,
 483,
 659,
 136,
 2,
 14,
 2,
 9,
 7,
 2022,
 55,
 164,
 40,
 7,
 45,
 36,
 389,
 31,
 7,
 2560,
 55,
 2,
 136,
 2,
 58,
 15,
 338,
 3,
 12,
 594,
 122,
 48,
 660,
 623,
 20,
 2,
 58,
 48,
 3,
 12,
 51,
 594,
 122,
 48,
 51,
 660,
 623,
 136,
 7,
 390,
 3,
 80,
 103,
 1618,
 44,
 81,
 484,
 2,
 80,
 41,
 2561,
 9,
 2,
 258,
 30,
 153,
 13,
 17,
 437,
 44,
 22,
 11,
 120,
 844,
 2,
 655,
 63,
 2023,
 136,
 28,
 93,
 2,
 69,
 5,
 3,
 1619,
 496,
 28,
 93,
 2,
 1392,
 136,
 74,
 90,
 66,
 309,
 27,
 10,
 1192,
 2,
 2,
 130,
 45,
 209,
 136,
 51,
 9,
 2,
 122,
 1,
 51,
 62,
 2,
 28,
 49,
 1,
 51,
 9,
 2,
 210,
 1,
 51,
 595,
 238,
 79,
 136,
 485,
 10,
 7,
 983,
 215,
 15,
 301,
 388,
 16,
 167,
 43,
 275,
 125,
 9,
 270,
 9,
 10,
 7,
 13,
 213,
 136,
 177,
 7,
 239,
 7,
 131,
 3,
 281,
 2,
 2,
 50,
 211,
 3,
 114,
 1,
 284,
 339,
 418,
 18,
 136,
 22,
 8,
 75,
 25,
 32,
 154,
 62,
 16,
 19,
 25,
 32,
 303,
 62,
 23,
 154,
 24,
 136,
 1,
 153,
 2563,
 169,
 199,
 7,
 16,
 1,
 391,
 154,
 737,
 136,
 2,
 170,
 7,
 24,
 16,
 5,
 140,
 ...]

In [24]:
max_len = max(len(x) for x in X)
print(max_len)

748

In [25]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
X_pad = pad_sequences(X, maxlen=max_len, padding='pre')

In [26]:
X_pad

array([[   0,    0,    0, ...,    0,    0,  732],
       [   0,    0,    0, ...,    0,  732,   61],
       [   0,    0,    0, ...,  732,   61,   30],
       ...,
       [   0,    0,    0, ...,    9,   19, 1333],
       [   0,    0,    0, ...,   19, 1333,    3],
       [   0,    0,    0, ..., 1333,    3,  174]], dtype=int32)

In [27]:
y = np.array(y)

In [28]:
X_pad.shape

(86549, 748)

In [29]:
y.shape

(86549,)

In [30]:
from tensorflow.keras.utils import to_categorical
y_categorical = to_categorical(y, num_classes=vocab_size)

In [31]:
y.shape

(86549,)

In [32]:
y_categorical.shape

(86549, 8214)

In [33]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM,Dense,SimpleRNN

In [34]:
embedding_dim = 50
rnn_utils = 128

In [35]:
rnn_model = Sequential()
rnn_model.add(
    Embedding(input_dim=vocab_size, output_dim=
    embedding_dim)
)
rnn_model.add(SimpleRNN(units=rnn_utils))
rnn_model.add(Dense(units=vocab_size,activation='softmax'))

In [36]:
rnn_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [37]:
rnn_model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [38]:
lstm_model = Sequential()
lstm_model.add(
    Embedding(input_dim=vocab_size,output_dim=embedding_dim)
)
lstm_model.add(LSTM(units=rnn_utils))
lstm_model.add(Dense(units=vocab_size, activation='softmax'))

In [39]:
lstm_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [40]:
rnn_model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [41]:
epochs = 10
batch_size = 128

In [42]:
LSTM_trained = lstm_model.fit(
    X_pad,y_categorical,
    epochs=epochs,
    batch_size=batch_size,
    validation_split=0.1
)

Epoch 1/10
609/609 ━━━━━━━━━━━━━━━━━━━━ 39s 53ms/step - accuracy: 0.0399 - loss: 6.6882 - val_accuracy: 0.0427 - val_loss: 6.6300
Epoch 2/10
609/609 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.0589 - loss: 6.2723 - val_accuracy: 0.0632 - val_loss: 6.4980
Epoch 3/10
609/609 ━━━━━━━━━━━━━━━━━━━━ 32s 52ms/step - accuracy: 0.0831 - loss: 6.0001 - val_accuracy: 0.0912 - val_loss: 6.3740
Epoch 4/10
609/609 ━━━━━━━━━━━━━━━━━━━━ 41s 53ms/step - accuracy: 0.1007 - loss: 5.7759 - val_accuracy: 0.0980 - val_loss: 6.3178
Epoch 5/10
609/609 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.1117 - loss: 5.5853 - val_accuracy: 0.1033 - val_loss: 6.2861
Epoch 6/10
609/609 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.1213 - loss: 5.4136 - val_accuracy: 0.1065 - val_loss: 6.3036
Epoch 7/10
609/609 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.1301 - loss: 5.2595 - val_accuracy: 0.1056 - val_loss: 6.3290
Epoch 8/10
609/609 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.1363 - loss: 5.1162 - val_accuracy: 0.1096 - val_loss: 6.3597
Epoch 9/10
609/609 ━━━━━━━━━━━━━━━━━━━━ 32s 52ms/step - accuracy: 0.1439 - loss: 4.9818 - val_accuracy: 0.1110 - val_loss: 6.3988
Epoch 10/10
609/609 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.1525 - loss: 4.8510 - val_accuracy: 0.1130 - val_loss: 6.4327

In [47]:
index_to_word ={}
for word, index in word_index.items():
  index_to_word[index] = word

In [48]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [49]:
def predictor(model,tokenizer,text,max_len):
  text = text.lower()
  seq = tokenizer.texts_to_sequences([text])[0]
  pad_seq = pad_sequences([seq], maxlen=max_len, padding="pre")

  pred = model.predict(pad_seq, verbose = 0)
  pred_index = np.argmax(pred)
  return index_to_word[pred_index]

In [50]:
seed_text = "who are you"
next_word = predictor(lstm_model, tokenizer,seed_text,max_len)
print(next_word)

are

In [56]:
def generate_quote(model,tokenizer,max_len,seed,total_words):
  seed_text = seed # Initialize seed_text with the seed parameter
  for _ in range(total_words):
    next_word = predictor(model,tokenizer,seed_text,max_len)
    if next_word ==" ":
      break
    seed_text += " "+ next_word
  return seed_text

In [59]:
seed = "are you a  "
generated_text = generate_quote(lstm_model, tokenizer, max_len, seed, 10)
print(generated_text)

are you a   man who was a man who reads who was a

In [60]:
import pickle
with open('tokenizer.pkl', 'wb') as f:
  pickle.dump(tokenizer, f)

In [61]:
with open("max_len.pkl", 'wb') as f:
  pickle.dump(max_len, f)